### ISSUE TITLE
sensor_msgsConfig.cmake Missing

### ISSUE THREAD

**Issue by FrittenIngenieur** [okalachev/vl53l1x_ros#10]
Hi together,
I am trying since two weeks to get the lib working. But I am not able to.

I am using noetic and when I do catkin_make I get the following error:

 +++ processing catkin package: 'vl53l1x'
-- ==> add_subdirectory(vl53l1x_ros/vl53l1x)
-- Could NOT find sensor_msgs (missing: sensor_msgs_DIR)
-- Could not find the required component 'sensor_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /home/pi/catkin_ws/devel/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "sensor_msgs" with
  any of the following names:

    sensor_msgsConfig.cmake
    sensor_msgs-config.cmake

  Add the installation prefix of "sensor_msgs" to CMAKE_PREFIX_PATH or set
  "sensor_msgs_DIR" to a directory containing one of the above files.  If
  "sensor_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  vl53l1x_ros/vl53l1x/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:838: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

If I search manually for the sensor_msgs lib, it is availble under /opt/ros/noetic/share/sensor_msgs

Can anybody help me please?

**Comment by okalachev** [comment]
Hi. Looks like you don’t have `sensor_msgs` package installed, which is weird, because it is actually included to ROS. Have you built and installed ROS properly? Have you sourced ROS’ `setup.bash`?

For RPi, we provide a prebuilt Debian package for this ROS package so it may be installed with `dpkg`. You can download it from here: http://packages.coex.tech/packages/buster/ros-noetic-vl53l1x/.

Also there is a prebuilt RPi image for Clover drone kit (https://github.com/CopterExpress/clover), that includes properly installed ROS Noetic and a lot of robotics stuff, related to UAV (including this package). Let me know if you consider using this image, so I can tell you how to disable auto starting Clover drone related stuff.

**Comment by FrittenIngenieur** [comment]
Hi,
thanks for your fast reply!

I have sourced setup.bash. Also I try find package in the console it is shown as available. Very weired. 

I think I will try your prebuilt image on my Raspi. It would be great if you can tell me how to disable the start of the drone related staff.
 Thank you very much for your support!

**Comment by okalachev** [comment]
To disable Clover services:

```bash
sudo systemctl stop clover
sudo systemctl disable clover
```

**Comment by FrittenIngenieur** [comment]
After some hours of testing and trying (including some problems with the sensor) I got it working with your prebuilt image.

Thank you very much for your help!
