### ISSUE TITLE
ubuntu 20.04 i2c failed

### ISSUE THREAD

**Issue by lurunawjan** [okalachev/vl53l1x_ros#11]
Hello, i have problem with the I2c in ubuntu. I'm using raspberry pi4 with ubuntu 20.04 and make connection for sensor using I2c in raspberry pi. then i got the error at the terminal said that "failed to open I2c bus 1" is there anyone know how to solve this problem. I really need help since I need to solve it urgently. Thank you

**Comment by okalachev** [comment]
Hi! 

You may try to debug your I2C bus using `i2c-tools`.

Get list of I2C busses - `i2cdetect -l`:

```
i2c-1   i2c             bcm2835 (i2c@7e804000)                  I2C adapter
```

Get list of devices on the bus 1 - `i2cdetect -y 1`:

```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- 29 -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --          
```

You can see the device with address 0x29, which is the rangefinder.

**Comment by lurunawjan** [comment]
Thank you for your reply. I manage to solve the problem. Since I'm new with ROS I wanted to ask how can I use the sensor with rviz? Thank you

**Comment by okalachev** [comment]
Run rviz on your computer with pointing `ROS_MASTER_URI` to your RPi's hostname; add `/vl53l1x/range` topic visualization.

Some more info here: https://clover.coex.tech/en/rviz.html#start-rviz

**Comment by lurunawjan** [comment]
I tried to use that but why it said that for frame [] fixed frame [map] does not exist

**Comment by okalachev** [comment]
In ROS, in order to visualize the sensor data each sensor should declare its pose in space (most often relative to the robot's body), using a TF frame. Please, address the [main TF documentation](http://wiki.ros.org/tf2) to learn details.

By default, the driver publishes an empty frame (`header.frame_id = ""`), so you should [configure](https://github.com/okalachev/vl53l1x_ros/blob/master/vl53l1x/launch/example.launch#L10) it manually in the launch-file.

The simplest way to see something is to put any string you want there (e. g. `rangefinder`) and set it as the rviz fixed frame name.
