### ISSUE TITLE
master branch vs. calibration branch

### ISSUE THREAD

**Issue by ghost** [okalachev/vl53l1x_ros#6]
Hi okalachev,

thanks a lot for your amazing package.
I use the master-branch for the vl53l1x in my Jetson Xavier, it works very well.

I'm wondering, whether I need to add an extra part about calibration by myself when I use the master-branch? What would be the negative influence if there were no calibration part?

Or should I directly use the calibration-branch instead?

Thank you in advance.
Best regards

**Comment by okalachev** [comment]
Hi! 

That's a good question. I refused making calibration branch a long time ago, and I can't remember for now why I did that. 

The user manual says:

> RefSPAD and crosstalk calibrations have to be performed whenever the customer adds a
protective cover glass on top of the VL53L1X module.
> Offset calibration has to be performed in all situations. It allows reflow and cover glass
effects to be compensated.

So since we don't use a protective cover glass, maybe I decided that offset calibration corrections are too minor to perform the calibration process.

Also, I'm not sure I actually tested the code in this branch.

If you could figure out in which situations calibration is actually worth it, and if this calibration code actually works, that would appreciated!
